### PR TITLE
fetch state of cityIO and update drawing features if needed

### PR DESCRIPTION
**Pull request by luftj**
this gets the current grid state of cityIO, checks if the grid has changed, and if yes, updates allthe features on the map to colour etc them accordingly

### CODE REVIEW

**Comment by RELNO** [comment]
> this gets the current grid state of cityIO

Is this done using hash matching?

**Comment by luftj** [comment]
> > this gets the current grid state of cityIO
> 
> Is this done using hash matching?

The front-end is updated only, when the grid hash has changed yet. Right now we still GET too much data regularly, I will fix this in a separate feature

**Comment by RELNO** [comment]
ok -- so just to align: cityio data (grid or modules) should be fetched given a field hash in meta has changed.  If this is the case, feel free to merge.

**Comment by luftj** [comment]
Alright, muddled it in here: 51f7645 
Merging now

**Pull request merged**
