### PR TITLE
Map and Layer Controls

### PR DESCRIPTION
**Pull request by illsio**
- I would suggest doing a lot of the configuration (mapbox and layers) via the config.json.
  That could always be a simple option if no cityio server is present.
- I included the standard maptastic.js @RELNO I was not able to make it work with your version.
- I included some files in case legends need to be displayed for the layers. If not please delete.
- The noise wms layer should work most of the time - the server in Hamburg had some minor performance issues the last week
- The typings.d.ts is not correctly included - couldn't make that work.

### CODE REVIEW

**Comment by yasushisakai** [comment]
overall this is great!!! Untill I have the time to look into the code...

 >     * I would suggest doing a lot of the configuration (mapbox and layers) via the config.json.
>       That could always be a simple option if no cityio server is present.

I totally agree having a config.json. Not to look into the future too much, but this file can define the "dependent" sim modules for that project, nothing close but similar to the concept of a package manager.
   
>     * The noise wms layer should work most of the time - the server in Hamburg had some minor performance issues the last week

great!!! 

>     * The typings.d.ts is not correctly included - couldn't make that work.

from our side, we are still very basic and still learning to embrace the full capabilities of typescirpt, although important, I think this is totally fine for now!

**Comment by RELNO** [comment]
@illsio great stuff -- UI and keystone works very well! Will explore other edits later today and merge asap

**Comment by RELNO** [comment]
@illsio thanks for the effort! -- going through the pull I've got a couple of questions:
- missing cityIO grid layer: the current `master` @https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/e777529a02134afdccbf8840d0b2ebdf8e1f0948 has cityIO 'grid' layer showing up on init, using `ModuleDataToMapHandler.getLayers(): [object]` to push it into mapbox as a layer. Can you explain the proposed process for loading layers into the basemap and we can restore this functionality?
- clicking twice on the noise layer returns: 
Screen Shot 2019-04-13 at 16 20 01

**Comment by illsio** [comment]
A grid never showed up on my map. I restored the inital ModuleDataToMapHandler on load code.
Toggling layers is fixed.

**Comment by RELNO** [comment]
@illsio great thanks -- https://github.com/CityScope/CSL_Hamburg_Grasbrook/pull/17/commits/b1817bead5f652a7a120e25bc875cc219285b2ef is restoring the grid with your edits. 
@yasushisakai we should look together at the way @illsio propagated his layer [using `config.json`] seems clean a simple to extend

**Pull request merged**
