### PR TITLE
City io push

### PR DESCRIPTION
**Pull request by luftj**
implemented sending user input to the cityIO grid and setting corresponding type mappings in header.
To do: the table data is fetched every 10 seconds and overwrites changes in the meantime. the update interval should be disabled (unneccesary? only the front end changes the grid)

### CODE REVIEW

**Comment by RELNO** [comment]
> To do: the table data is fetched every 10 seconds and overwrites changes in the meantime. the update interval should be disabled (unneccesary? only the front end changes the grid)

if the tool is online only (no TUI), then there is no need for constant cityIO grid retrieval. However, this forces only single user interaction.

**Comment by luftj** [comment]
> if the tool is online only (no TUI), then there is no need for constant cityIO grid retrieval. However, this forces only single user interaction.

I understand. 
A. So what is the expected behaviour, when a cell changes in 2 places at the same time? I.e. the user changes a cell in the front-end while the state on cityIO changes. Just overwrite? 
B. And how does the TUI reflect set cells, where there is no physical object present?

**Comment by luftj** [comment]
fixed in fb9366630f065b62d3a469358931e107186d34b0

> 
> if the tool is online only (no TUI), then there is no need for constant cityIO grid retrieval. However, this forces only single user interaction.

**Comment by RELNO** [comment]
>  This can be a problem, when people are working on different subsets of the grid, since we can only write the whole grid, not single cells.

This taps into the the question of what is an MVP of this project. if we hope that in each design firm, more than 1 instance will be active, we'll face the issue of not just overwriting but also spinning  N modules computation per firm. I don't see how this can be supported soon. 

> B. How does the TUI reflect set cells, where there is no physical object present

not sure I understand

**Comment by luftj** [comment]
> This taps into the the question of what is an MVP of this project. if we hope that in each design firm, more than 1 instance will be active, we'll face the issue of not just overwriting but also spinning N modules computation per firm. I don't see how this can be supported soon.

We only need to spin one module per simulation per table, not per user. And we run a docker for each table, with a different endpoint configured. That's the IaaS way.

> > B. How does the TUI reflect set cells, where there is no physical object present
> not sure I understand

When a grid cell is changed with the web front-end, no LEGO brick will magically appear on a cityscope. Was it planned to use both at once for a given table?

**Comment by RELNO** [comment]
> We only need to spin one module per simulation per table, not per user

> When a grid cell is changed with the web front-end, no LEGO brick will magically appear on a cityscope. Was it planned to use both at once for a given table?

Are there tables (TUIs) planned for this tool? We were aiming for it to be a mobile first, multi-user tool.

**Comment by luftj** [comment]
> > When a grid cell is changed with the web front-end, no LEGO brick will magically appear on a cityscope. Was it planned to use both at once for a given table?
> 
> Are there tables (TUIs) planned for this tool? We were aiming for it to be a mobile first, multi-user tool.

Then it's okay. I think having a table (TUI) and web-app access the same table at the same doesn't make too much sense either way.

**Pull request merged**
