### PR TITLE
Make work on linux

### PR DESCRIPTION
**Pull request by luftj**
fixes issue https://github.com/CityScope/CSL_Hamburg_Grasbrook/issues/74

### CODE REVIEW

**Comment by luftj** [comment]
works un ubuntu. See https://github.com/CityScope/CSL_Hamburg_Grasbrook/runs/341760757

**Comment by andredaa** [comment]
maptastic no longer working. 
If I click on the "maptastic" icon in the map-menu: ERROR ReferenceError: "numeric is not defined"
when trying to load maptastic.
Somehow numeric might need to be linked to this:   node_modules/numeric/numeric-1.2.6.min.js
see : https://github.com/austince/maptasticjs/commit/82ce16aa8b685aaf1a389cd8322785b25e6cd360#diff-3ec40a1e2a924ba4ba6521185d17b0f2R37

**Comment by RELNO** [comment]
My suggestion is to avoid Maptastic all in all in this point - there is no plan to project the app on a table now, and if we do we can revisit it via native CSS3d api.
As for this specific issue: numeric is a library embedded inside MT. My guess is that the way it's loaded at init does not conform to es6 module imports.

**Comment by luftj** [comment]
should be fixed with maptastic 3.0.0.

**Pull request closed without merging**
