### PR TITLE
Added deckgl layer for GAMA sim 

### PR DESCRIPTION
**Pull request by RELNO**
Following the Trips layer logic, this is a verbose copy. We can think of a cleaner way of deploying multiple layers of the same type.

### CODE REVIEW

**Comment by illsio** [comment]
Yes - the amount of duplicate code makes me shiver.
createTripsLayer() could get passed all parameters that differ between gama and trips.

**Comment by illsio** [comment]
The Gama Layer doesnt work for me

**Comment by RELNO** [comment]
> We could put all the parameters from loopLength to currentTime in the json, pass that to the createTripsLayer() method and only have one class for gama and trips. The more general problem is, that this might work in this case, but not when the calculation (renderLayers()) gets more complicated. That cannot be passed through a json. It will always be a bit hacky ...
How much will future versions deck.gl layers differ from these two?

Yes, layers injection slowly becomes too complex to follow (config.json, layer-loader.service, CSlayers etc etc). I'm in favor of opening this and finding a more refactor-able way to inject layers. 
And yes, deckgl might become more complex later with other layer types (hexagon heatmaps for ABM ..)

**Comment by RELNO** [comment]
@illsio I'll merge, and we can deal with simpler layer integration (and leaner codebase) next

**Pull request merged**
