### PR TITLE
Raw implementation of animated  deckgl layer for ABM 

### PR DESCRIPTION
**Pull request by RELNO**
@illsio for now, the deckgl layer is stashed at the end of basemap comp. 
This should (and probably other functions) be relocated to another service / comp. Would be great if you could look into this. 
As well, what is the way to add a mapbox layer to the control panel if it is not a pure JSON `CsLayer` object?

### CODE REVIEW

**Comment by illsio** [comment]
Please push the deck.gl dependencies - package.json
What kind of Layer are we talking about? Can you provide an example?

**Comment by RELNO** [comment]
@illsio: https://github.com/CityScope/CSL_Hamburg_Grasbrook/pull/57/commits/357ffc8a4d84ae88b297062fb42ab77f65167fe5

The layer is a costume mapbox gl layer that renders using deck: https://citysciencenetwork.slack.com/files/UD70K7E6Q/FLRR62H6J/untitled.mov

**Comment by illsio** [comment]
Are we talking about the code in the deckgl function in the basemap`?
Would you like to have that in the config?

**Comment by RELNO** [comment]
Yes, if you run it you'd see a NYC demo. My question is more general -- how do we include layers that are not pure json in the toggle list.

**Comment by illsio** [comment]
@RELNO feel free to merge

**Comment by RELNO** [comment]
@illsio great thanks

**Pull request merged**
