### PR TITLE
Grid localstorage

### PR DESCRIPTION
**Pull request by illsio**

### CODE REVIEW

**Comment by illsio** [comment]
Hope that works - had to do a lot of conflict resolving.

**Comment by RELNO** [comment]
Yes, just saw it. should be ok now

**Comment by RELNO** [comment]
upon merging, these names are missing -- can you fix directly on master? 
Screen Shot 2019-07-30 at 10 19 20

**Comment by illsio** [comment]
i will

**Comment by illsio** [comment]
should be resolved

**Pull request merged**
