### PR TITLE
Show stormwater results

### PR DESCRIPTION
**Pull request by andredaa**
Add chart results for stormwater
Refactor chart menu component to display multiple result sets

### CODE REVIEW

**Comment by RELNO** [comment]
Getting error upon click on droplet icon
Screen Shot 2020-01-06 at 17 12 44

**Comment by andredaa** [comment]
which user are you logging in with? cannot reproduce this. Might be related to the results received from the stormwater model.

**Comment by andredaa** [comment]
> Getting error upon click on droplet icon
> Screen Shot 2020-01-06 at 17 12 44

I pushed a commit with changes ensuring that only numbers are passed to the chart. If the stormwater module publishes a non-numeric result, the chart will show a 0 as result.

**Comment by andredaa** [comment]
Error only showed in Chrome, not Firefox.
Updated function to set target bar.

**Comment by RELNO** [comment]
> I pushed a commit with changes ensuring that only numbers are passed to the chart. If the stormwater module publishes a non-numeric result, the chart will show an empty graph as result.

This might have to do with the new grid size. This probably broke the calc of the module, hence to non-number values.Thanks for fencing it.

**Comment by andredaa** [comment]
> > I pushed a commit with changes ensuring that only numbers are passed to the chart. If the stormwater module publishes a non-numeric result, the chart will show an empty graph as result.
> 
> This might have to do with the new grid size. This probably broke the calc of the module, hence to non-number values.Thanks for fencing it.

Turns out the problem was that the stormwater results have no target values. The d3 chart was always set with target lines to render though. 
Made a indentifier now whether a chart has target values or not.

**Pull request merged**
